### ISSUE TITLE
LUA Error when Ignis casts Flame Jet in Ulduar 10 and 25

### ISSUE THREAD

**Issue by Gordnfreeman** [DeadlyBossMods/DBM-WoTLKC#14]
During the Ignis encounter whenever he casts Flame Jets a LUA error will appear. I attached the error below in a screenshot.

![image_2023-01-20_214944072](https://user-images.githubusercontent.com/1406430/213840577-da89d554-4388-464f-8e97-a59d736e97c4.png)

**Comment by MysticalOS** [comment]
this is already fixed, update the mod
