### ISSUE TITLE
Yogg-Saron brain timers

### ISSUE THREAD

**Issue by pjasnorzewski1** [DeadlyBossMods/DBM-WoTLKC#15]
**Describe the bug**
Yogg-Saron brain portals timers continue to count down during phase 3 where boss is <= 30% health.

**Which version of DeadlyBossMods are you using?**
DBM-3.4.27-wrath

**Comment by MysticalOS** [comment]
I'll try to look at this bug again, I tried to fix it years ago on retail, for some reason P3 detection still fails half the time.

**Comment by MysticalOS** [comment]
Yeah I still can't find any explanation to cause. On removal of shadow barrier (start of p3) the portal timers are stopped. and I even sync the event to work around issue where if you're in brain room, you don't get event for shadow barrier being removed. yet this bug still happens. I wonder if sometimes shadow barrier being removed fails to appear in combat log at all (for anyone in raid)

**Comment by pjasnorzewski1** [comment]
Does DBM generate any logs in a text file I can share that would help figure this out? I did see this happen on my DBM in the latest run - I assume if DBM is synced with all party/raid members, it wouldn't necessarily be my instance of DBM causing timers to restart?

**Comment by MysticalOS** [comment]
did you try latest alpha? Only thing left I could try is just prevent them from restarting in P3.

**Comment by pjasnorzewski1** [comment]
Sorry, I was referring to the run from yesterday. I haven't tried the alpha yet, but I can do it in my run tomorrow.

**Comment by MysticalOS** [comment]
Yep I can confirm cause of this bug now and it's fixed in latest update so closing issue.
