### ISSUE TITLE
DBM 3.4.35 Wrath crashing WoW client during Ulduar Thorim 25 man encounter

### ISSUE THREAD

**Issue by hnfmr** [DeadlyBossMods/DBM-WoTLKC#17]
**Describe the bug**
DBM crashing my WoW client multiple times during the Thorim (Ulduar 25) encounter

**Do you have an error log of what happened?**

1x DBM-Ulduar/Thorim.lua:141: attempt to compare nil with number
[string "@DBM-Ulduar/Thorim.lua"]:141: in function `OnSync'
[string "@DBM-Core/DBM-Core.lua"]:11284: in function `ReceiveSync'
[string "@DBM-Core/DBM-Core.lua"]:11259: in function `SendSync'
[string "@DBM-Ulduar/Thorim.lua"]:136: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:968: in function <DBM-Core/DBM-Core.lua:955>

Locals:
Skipped (In Encounter)

**To Reproduce**
1. Thorim Ulduar 25 man encounter
2. Crash

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
Everyone who's getting this error seems to be running addonSkins, disable that and retry

**Comment by Sakatard** [comment]
happening on algalon too but only after the latest DBM wotlkc commit

**Comment by MysticalOS** [comment]
the other user who posted this error got many other errors too not just this one and only work around was disabling addonskins. Do either of you have other errors that happened BEFORE this one? I think comms are only broken because something else broke first.

**Comment by Sakatard** [comment]
> the other user who posted this error got many other errors too not just this one and only work around was disabling addonskins. Do either of you have other errors that happened BEFORE this one? I think comms are only broken because something else broke first.

no previous lua errors and this problem did not persist, i just had to reload and the timers were fine again (for the record the timers did show even when it was broken just not on pull for algalon)
