### ISSUE TITLE
3.4.38 WOTLKC release missing DBM-Party-WotLK folder

### ISSUE THREAD

**Issue by jmrd98** [DeadlyBossMods/DBM-WoTLKC#18]
**Describe the bug**

Download from either curseforge or github and find that the 3.4.38 release is missing the DBM-Party-WotLK folder. This folder is present in the 3.4.37 release.

**Do you have an error log of what happened?**

No error as a module is simply missing.
**To Reproduce**

see description.
**Screenshots**
n/a
**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**
No, I did not.
**Which version of DeadlyBossMods are you using?**
3.4.38
**Was it working in a previous version? If yes, which was the last good one?**
3.4.37
**Additional context**
I was able to work around it easily enough by adding the folder manually from the dbm-dungeons download. My guess is that the CI script isn't getting the external source in the right place for some reason.

**Comment by QartemisT** [comment]
This has now been fixed as of latest alpha build. I'm sure @MysticalOS will likely create a new release later today ;D
