### ISSUE TITLE
mim firestarter fire timer

### ISSUE THREAD

**Issue by Raulfin** [DeadlyBossMods/DBM-WoTLKC#20]
**Describe the bug**

The new fire timer is off by 1-3s, and drifts more off the longer the fight lasts.

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

**Comment by MysticalOS** [comment]
this is why I deleted it years ago. but users insisted they wanted the timer back despite it's problems

it's not fixable, outside of deleting it again if it annoys me again.

**Comment by Raulfin** [comment]
it's nice to have even if it is a tiny bit off, even off by a couple seconds it's really helpful for between phases to try to get ppl to stack up some. have had a few ppl die stacking to soon and then afk in fire ><

**Comment by MysticalOS** [comment]
I just checked code. DBM doesn't have firestarter timer. it was never merged back in. Someone made a PR for it at one point but then decided to cancel PR cause it needed more work. Then never heard from them again. I know I had put a timer in years ago and then deleted it do to the drift issue (it has no event to resync it and it had in-precise timing so it'd not even match up pull to pull).

**Comment by Raulfin** [comment]
hmm okay weird, yeah just saw it's not in the code too, the timer for fire is with the other dbm timers, i'll watch it closer on my next 10 and 25 runs tuesday and wednesday and post back.

**Comment by Raulfin** [comment]
yeah sry timer was from Tems.
