### ISSUE TITLE
ICC Lich King 

### ISSUE THREAD

**Issue by holypalaswe** [DeadlyBossMods/DBM-WoTLKC#22]
Classic WotLK PTR Icecrown Lich King heroic 25m fight

Describe the bug

Shadow Trap warning on Lich King bugs out when he casts disease on a target same time. Shows shadow trap say on disease target and nothing on the target of the shadow trap.
Should show /say shadow trap warning on the actual targeted player. BigWigs is doing this OK for other raider.

Which version of DeadlyBossMods are you using?
3.4.51 alpha 2023/08/29 13:08:28

**Comment by MysticalOS** [comment]
I've added same filter tech as general vezax for mark of faceless and shadowcrash (same problem, boss can target both players in same GCD basically). I looked at what BW is doing and they delay the scan by 100ms. I'd prefer not to do that, i think starting scan instantly and filtering plague target is better approach for a faster yell/warning. Then if it actually cannot find another target immediately, fallback to the plague target after the delay.

anyways, test alpha in next round you do

**Comment by holypalaswe** [comment]
From testing it seems like only Gunship & Blood Prince (for some reason) utilizes bossframes atm.

Ty for fast response, will test it tomorrow!

**Comment by holypalaswe** [comment]
Still gave false shadow trap /say warning and missed the correct target when plague coincided with shadow trap. (with 3.4.50-3-gd6ec53d-wrath. (3.4.51 alpha ingame) on everyone in raid)).

**Comment by MysticalOS** [comment]
Oh it could be a raise condition if the debuff and trap literally go out in same frame, so it'd cause the target filter to still not be used since it's not updated yet. I'm gonna add a 10ms delay on target scan purely to solve any possible race condition in same frame casts.

**Comment by MysticalOS** [comment]
thanks for quick feedback and testing.

**Comment by holypalaswe** [comment]
We had more tries and while it was working most of the time, we had maybe one out of 50 shadow trap that was not announced by DBM (no /say, no chat announce, no nearby warning).
Also same thing with Defile P2, occassionaly wrong (showed a tank as target instead of not showing up at all though).
