### ISSUE TITLE
No announcements on boss dungeons since 3.4.53 update

### ISSUE THREAD

**Issue by jdelvare** [DeadlyBossMods/DBM-WoTLKC#23]
**Describe the bug**
Since I updated DBM to version 3.4.53-wrath, I don't get any announcements when fighting bosses in dungeons.

I didn't get to raid since the update, so I can't tell whether the issue is limited to dungeons or also affects raids.

**Do you have an error log of what happened?**
No log. I reverted to the previous version (3.4.52-wrath) for the time being. If it helps, I can update to the newer version again and enable console errors.

**To Reproduce**
Install DBM-3.4.53-wrath and run any WotLK dungeon.

**Comment by QartemisT** [comment]
Hi there.

As per some recent changes, you will need to install the "DBM Dungeons" pack for dungeon content. This is to streamline development of it, and prevent some ugliness with outdatedness etc.

You can find DBM Dungeons pack located here;
* https://www.curseforge.com/wow/addons/deadly-boss-mods-dbm-dungeons
* https://addons.wago.io/addons/deadly-boss-mods-dbm-old-dungeon-mods

**Comment by jdelvare** [comment]
Thanks for the quick reply! I'll install the extra add-on.

Maybe this change could be made a little more visible on the deadly-boss-mods download page on curseforge, or maybe even a line in the chat when loading DBM-Core for a couple versions.

**Comment by MysticalOS** [comment]
It is visible on download page on curse. Also first time you enter a dungeon if dungeon mods aren't installed it should also add a message to chat saying you are doing a current content dungeon with no current content dungeon mods installed.
