### ISSUE TITLE
Wrath Classic nil Options reference

### ISSUE THREAD

**Issue by Road-block** [DeadlyBossMods/DBM-WoTLKC#25]
**Describe the bug**

**Do you have an error log of what happened?**

```
1x DBM-Core/DBM-Core.lua:11165: attempt to index field 'Options' (a nil value)
[string "@DBM-Core/DBM-Core.lua"]:11165: in function `Start'
[string "@DBM-Party-WotLK/PitofSaron/ScourgelordTyrannus.lua"]:140: in function `handler'
[string "@DBM-Core/DBM-Core.lua"]:1062: in function <DBM-Core/DBM-Core.lua:1049>

Locals:
self = <table> {
 timer = 31
 owner = <table> {
 }
 bar = <table> {
 }
}
timer = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'Options' (a nil value)"
```

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**
`DBM 3.4.54 alpha (2023/11/03 03:07:41)`

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**
I don't think it's this specific module only, seen the same error elsewhere.

**Comment by MysticalOS** [comment]
Fixed in latest alpha
