### ISSUE TITLE
Ruby Sanctum Halion - Timers are faded out for my realm.

### ISSUE THREAD

**Issue by holypalaswe** [DeadlyBossMods/DBM-WoTLKC#26]
Whenever I entered Twilight Realm, the timers for twilight realm were faded out.
https://www.twitch.tv/videos/2032495481?t=2h27m3s

DBM version 3.4.56 alpha (2024/01/14 03:25:25)

**Comment by MysticalOS** [comment]
no idea, code looks fine, so if it's not working it has to be a bug I cannot fix, so i'll probably scrap the timer fading feature.

**Comment by holypalaswe** [comment]
I tried unticking the boss option "Show warning/timers for phase you aren't in as well" but it didn't change anything.

**Comment by MysticalOS** [comment]
Oh I found problem, new alpha going out to fix it

**Comment by holypalaswe** [comment]
Working correctly now! :)
