### ISSUE TITLE
DBM-3.4.10-3-gf80295c-wrath - Errors on login

### ISSUE THREAD

**Issue by quetzalin** [DeadlyBossMods/DBM-WoTLKC#6]
**Describe the bug**
Getting the next errors when i log-in with the latest alpha DBM-3.4.10-3-gf80295c-wrath

**Do you have an error log of what happened?**

6x DBM-Core\DBM-Core-66405cd.lua:7351: attempt to index field 'specRoleTable' (a nil value)
[string "@DBM-Core\DBM-Core-66405cd.lua"]:7351: in function `?'
[string "@DBM-Core\DBM-Core-66405cd.lua"]:7491: in main chunk

Locals:
self = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core\DBM-Core.lua:4271
 StopLogging = <function> defined @DBM-Core\DBM-Core.lua:5511
 FindScenarioIDs = <function> defined @DBM-Core\DBM-Core.lua:6481
 GetNumGuildPlayersInZone = <function> defined @DBM-Core\DBM-Core.lua:2327
 VibrateController = <function> defined @DBM-Core\DBM-Core.lua:6447
 FindDungeonMapIDs = <function> defined @DBM-Core\DBM-Core.lua:6473
 GetUnitIdFromGUID = <function> defined @DBM-Core\DBM-Core.lua:2571
 CopyProfile = <function> defined @DBM-Core\DBM-Core.lua:1834
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core\DBM-Core.lua:4622
 CHAT_MSG_WHISPER = <function> defined @DBM-Core\DBM-Core.lua:6219
 SendPVPTimers = <function> defined @DBM-Core\DBM-Core.lua:6024
 DeleteProfile = <function> defined @DBM-Core\DBM-Core.lua:1851
 GetRaidRoster = <function> defined @DBM-Core\DBM-Core.lua:2363
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:4383
 FireEvent = <function> defined @DBM-Core\DBM-Core.lua:1742
 SCENARIO_COMPLETED = <function> defined @DBM-Core\DBM-Core.lua:3244
 IsEnabled = <function> defined @DBM-Core\DBM-Core.lua:6304
 GetMyPlayerInfo = <function> defined @DBM-Core\DBM-Core.lua:2417
 ADDON_LOADED = <function> defined @DBM-Core\DBM-Core.lua:1425
 IconNumToTexture = <function> defined @DBM-Core\DBM-Core.lua:6462
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:2298
 GetBossUnitId = <function> defined @DBM-Core\DBM-Core.lua:2554
 AddDefaultOptions = <function> defined @DBM-Core\DBM-Core.lua:2641
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core\DBM-Core.lua:3573
 FilterRaidBossEmote = <function> defined @DBM-Core\DBM-Core.lua:1258
 RequestTimers = <function> defined @DBM-Core\DBM-Core.lua:5923
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core\DBM-Core.lua:3222
 CheckNearby = <function> defined @DBM-Core\DBM-Core.lua:2601
 CHAT_MSG_MONSTER_YELL = <function> defined @DBM-Core\DBM-Core.lua:4587
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3152
 ReleaseRevision = 20220914000000
 RegisterShortTermEvents = <function> defined @DBM-Core\DBM-Core.lua:1196
 LOADING_SCREEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:3409
 GetUnitFullName = <function> defined @DBM-Core\DBM-Core.lua:2422
 UNIT_HEALTH_FREQUENT = <function> defined @DBM-Core\DBM-Core.lua:5082
 UNIT_DIED = <function> defined @DBM-Core\DBM-Core.lua:5891
 ReceiveCombatInfo = <function> defined @DBM-Core\DBM-Core.lua:5951
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:3184
 RegisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1757
 FindInstanceIDs = <function> defined @DBM-Core\DBM-Core.lua:6477
 UnregisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1766
 CHALLENGE_MODE_RESET = <function> defined @DBM-Core\DBM-Core.lua:3430
 RepositionFrames = <function> defined @DBM-Core\DBM-Core.lua:1874
 LFG_ROLE_CHECK_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3143
 Disable = <function> defined @DBM-Core\DBM-Core.lua:6292
 ReceiveTimerInfo = <function> defined @DBM-Core\DBM-Core.lua:5960
 BN_CHAT_MSG_ADDON = <function> defined @DBM-Core\DBM-Core.lua:4324
 ModLists = <table> {
 }
 strFromTime = <function> defined @DBM-Core\DBM-Core.lua:788
 GetCIDFromGUID = <function> defined @I

And also:

6x DBM-Core\DBM-Core-66405cd.lua:3106: attempt to call method 'UpdateWarningOptions' (a nil value)
[string "@DBM-Core\DBM-Core-66405cd.lua"]:3106: in function <DBM-Core\DBM-Core.lua:3083>
[string "@DBM-Core\DBM-Core-66405cd.lua"]:1433: in function `handler'
[string "@DBM-Core\DBM-Core-66405cd.lua"]:927: in function <DBM-Core\DBM-Core.lua:914>

Locals:
self = <table> {
 CHAT_MSG_ADDON_LOGGED = <function> defined @DBM-Core\DBM-Core.lua:4271
 StopLogging = <function> defined @DBM-Core\DBM-Core.lua:5511
 FindScenarioIDs = <function> defined @DBM-Core\DBM-Core.lua:6481
 GetNumGuildPlayersInZone = <function> defined @DBM-Core\DBM-Core.lua:2327
 VibrateController = <function> defined @DBM-Core\DBM-Core.lua:6447
 FindDungeonMapIDs = <function> defined @DBM-Core\DBM-Core.lua:6473
 GetUnitIdFromGUID = <function> defined @DBM-Core\DBM-Core.lua:2571
 CopyProfile = <function> defined @DBM-Core\DBM-Core.lua:1834
 CHAT_MSG_MONSTER_EMOTE = <function> defined @DBM-Core\DBM-Core.lua:4622
 CHAT_MSG_WHISPER = <function> defined @DBM-Core\DBM-Core.lua:6219
 SendPVPTimers = <function> defined @DBM-Core\DBM-Core.lua:6024
 DeleteProfile = <function> defined @DBM-Core\DBM-Core.lua:1851
 DungeonMusic = <table> {
 }
 ShowUpdateReminder = <function> defined @DBM-Core\modules\UpdateReminder.lua:76
 GetRaidRoster = <function> defined @DBM-Core\DBM-Core.lua:2363
 PLAYER_REGEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:4383
 FireEvent = <function> defined @DBM-Core\DBM-Core.lua:1742
 CreateModLocalization = <function> defined @DBM-Core\modules\objects\Localization.lua:89
 SCENARIO_COMPLETED = <function> defined @DBM-Core\DBM-Core.lua:3244
 IsEnabled = <function> defined @DBM-Core\DBM-Core.lua:6304
 GetMyPlayerInfo = <function> defined @DBM-Core\DBM-Core.lua:2417
 ADDON_LOADED = <function> defined @DBM-Core\DBM-Core.lua:1425
 IconNumToTexture = <function> defined @DBM-Core\DBM-Core.lua:6462
 BattleMusic = <table> {
 }
 INSTANCE_GROUP_SIZE_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:2298
 AddDefeatSound = <function> defined @DBM-Core\modules\Sounds.lua:106
 GetBossUnitId = <function> defined @DBM-Core\DBM-Core.lua:2554
 AddDefaultOptions = <function> defined @DBM-Core\DBM-Core.lua:2641
 UPDATE_MOUSEOVER_UNIT = <function> defined @DBM-Core\DBM-Core.lua:3573
 InfoFrame = <table> {
 }
 FilterRaidBossEmote = <function> defined @DBM-Core\DBM-Core.lua:1258
 RequestTimers = <function> defined @DBM-Core\DBM-Core.lua:5923
 UPDATE_BATTLEFIELD_STATUS = <function> defined @DBM-Core\DBM-Core.lua:3222
 CheckNearby = <function> defined @DBM-Core\DBM-Core.lua:2601
 CHAT_MSG_MONSTER_YELL = <function> defined @DBM-Core\DBM-Core.lua:4587
 LFG_PROPOSAL_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3152
 ReleaseRevision = 20220914000000
 RegisterShortTermEvents = <function> defined @DBM-Core\DBM-Core.lua:1196
 LOADING_SCREEN_DISABLED = <function> defined @DBM-Core\DBM-Core.lua:3409
 GetUnitFullName = <function> defined @DBM-Core\DBM-Core.lua:2422
 UNIT_HEALTH_FREQUENT = <function> defined @DBM-Core\DBM-Core.lua:5082
 UNIT_DIED = <function> defined @DBM-Core\DBM-Core.lua:5891
 ReceiveCombatInfo = <function> defined @DBM-Core\DBM-Core.lua:5951
 PLAYER_SPECIALIZATION_CHANGED = <function> defined @DBM-Core\DBM-Core.lua:3184
 RegisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1757
 FindInstanceIDs = <function> defined @DBM-Core\DBM-Core.lua:6477
 UnregisterCallback = <function> defined @DBM-Core\DBM-Core.lua:1766
 CHALLENGE_MODE_RESET = <function> defined @DBM-Core\DBM-Core.lua:3430
 RepositionFrames = <function> defined @DBM-Core\DBM-Core.lua:1874
 LFG_ROLE_CHECK_SHOW = <function> defined @DBM-Core\DBM-Core.lua:3143
 Disable = 

3009x (null)

**Comment by MysticalOS** [comment]
Fixed in https://github.com/DeadlyBossMods/DBM-Unified/commit/c154c71663c23bc53e3b908fae10d8cadd75ffbf
