### ISSUE TITLE
10 man KT Frost Blast timer

### ISSUE THREAD

**Issue by CaveJohnsonn** [DeadlyBossMods/DBM-WoTLKC#7]
The timer for 10 man Naxx KT Frost Blast is wildly inaccurate. I've updated DBM and completely fresh installed it. It'll says 20 seconds until blast and then the blast immediately goes off and sometime it'll say it's happening now but doesn't happen for 10+ more seconds.

**Comment by MysticalOS** [comment]
Frost blast has a 35-77.7 variation

yes it's that bad. all cooldown shows is the window of time it won't be cast, not when it will. that's all that can be done with a timer so wildly variable.

https://classic.warcraftlogs.com/reports/9tpQMmRZTK36yLCq#fight=last&pins=2%24Off%24%23244F4B%24expression%24ability.id%20%3D%2027808%20and%20type%20%3D%20%22cast%22&view=events

**Comment by MysticalOS** [comment]
I made timer off by default so it's less confusing, if you want to re-enable it you can but it won't make it any better.
