### ISSUE TITLE
Incompatible

### ISSUE THREAD

**Issue by tysonarmy** [DeadlyBossMods/DBM-WoTLKC#9]
**Describe the bug**

**Do you have an error log of what happened?**

**To Reproduce**

**Screenshots**

**Did you try having DeadlyBossMods as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of DeadlyBossMods are you using?**

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**
I have no I dea what is causing this, I have updated, reinstalled, reloaded, everything I can think of the addon refuses to work and lists itself as incompatible.

**Comment by MysticalOS** [comment]
Are you actually playing wrath classic or retail? are you installing the correct mods (DBM Core for wrath classic, not wrath mods for retail)
